# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EdiwnMainUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        
        Form.resize(1237, 789)
        Form.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Listening = QtWidgets.QLabel(Form)
        self.Listening.setGeometry(QtCore.QRect(270, 125, 731, 481))
        self.Listening.setText("")
        self.Listening.setPixmap(QtGui.QPixmap("C:\\Users\\Kaushik\\Documents\\Programming\\ALS_Edwin\\EdwinUimages\\Listening.gif"))
        self.Listening.setObjectName("Listening")
        self.Loading = QtWidgets.QLabel(Form)
        self.Loading.setGeometry(QtCore.QRect(270, 125, 731, 481))
        self.Loading.setText("")
        self.Loading.setPixmap(QtGui.QPixmap("C:\\Users\\Kaushik\\Documents\\Programming\\ALS_Edwin\\EdwinUimages\\Recognizing.gif"))
        self.Loading.setObjectName("Loading")
        self.Speaking = QtWidgets.QLabel(Form)
        self.Speaking.setGeometry(QtCore.QRect(270, 125, 731, 481))
        self.Speaking.setText("")
        self.Speaking.setPixmap(QtGui.QPixmap("C:\\Users\\Kaushik\\Documents\\Programming\\ALS_Edwin\\EdwinUimages\\Speaking.gif"))
        self.Speaking.setObjectName("Speaking")
        self.Open_terminal = QtWidgets.QPushButton(Form)
        self.Open_terminal.setGeometry(QtCore.QRect(1200, 10, 31, 31))
        self.Open_terminal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Open_terminal.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Kaushik\\Documents\\Programming\\ALS_Edwin\\EdwinUimages\\Open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Open_terminal.setIcon(icon)
        self.Open_terminal.setIconSize(QtCore.QSize(30, 30))
        self.Open_terminal.setObjectName("Open_Terminal")       
        self.Close_Terminal = QtWidgets.QPushButton(Form)
        self.Close_Terminal.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.Close_Terminal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Close_Terminal.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\Kaushik\\Documents\\Programming\\ALS_Edwin\\EdwinUimages\\Close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Close_Terminal.setIcon(icon1)
        self.Close_Terminal.setIconSize(QtCore.QSize(30, 30))
        self.Close_Terminal.setObjectName("Close_Terminal")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(840, 10, 391, 771))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.OutputBox = QtWidgets.QPlainTextEdit(self.frame)
        self.OutputBox.setGeometry(QtCore.QRect(10, 10, 371, 701))
        self.OutputBox.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);")
        self.OutputBox.setObjectName("OutputBox")
        self.InputBox = QtWidgets.QLineEdit(self.frame)
        self.InputBox.setGeometry(QtCore.QRect(10, 720, 291, 31))
        self.InputBox.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);")
        self.InputBox.setObjectName("InputBox")
        self.EnterButton = QtWidgets.QPushButton(self.frame)
        self.EnterButton.setGeometry(QtCore.QRect(310, 720, 71, 31))
        self.EnterButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        font = QtGui.QFont()
        font.setFamily("Blatant")
        font.setBold(True)
        self.EnterButton.setFont(font)
        self.EnterButton.setStyleSheet("color: rgb(170, 0, 0);")
        self.EnterButton.setObjectName("EnterButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowIcon(QtGui.QIcon("C:\\Users\\Kaushik\\Documents\\Programming\\ALS_Edwin\\EdwinUimages\\logo.png"))
        Form.setWindowTitle(_translate("Form", "Augmented Learning System"))
        self.EnterButton.setText(_translate("Form", "E N T E R"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
